require 'comfortable_mexican_sofa'
require 'devise'
require 'cancan'

require_relative 'cms/fortress/application_controller_methods'
require_relative 'cms/fortress/page_methods'
require_relative 'cms/fortress/rails/engine'
require_relative 'cms/fortress/auth'
require_relative 'cms/fortress/content_renderer'
require_relative 'cms/fortress/comfortable_mexican_sofa'
require_relative 'cms/fortress/devise'
require_relative 'cms/fortress/routing'
require_relative '../app/models/cms_ability'
